### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by jansivans** [RusKrim/jr_js_task#1]
Thanks for the work! You are having a good start.
Your quiz test looks good - everything was answered correctly.
Speaking about coding task, you have only one endpoint which I can check.
It does what was requested, however, there is one small issue.
When a server starts, it immediately gets a BTC price inside `jsonEur` and never changes it.
So if server was started at the morning and price of BTC was `9000`, by the night it will stay the same even if a real price has changed.

You are having a great potential and it would be awesome if you could fix this issue and add two more endpoints.

**Comment by RusKrim** [comment]
Good evening!

Sure I will fix it and finish it. I will check some tutorials to get better
understanding

**Comment by RusKrim** [comment]
Good morning,

The data that I have received from the request should be dynamic( the data
should change even without reloading page, sending another request to the
endpoint)?

**Comment by jansivans** [comment]
Hi. 
User should receive latest data as he sends his request.
So reloading page (i.e. sending other request) should return latest data.

**Comment by RusKrim** [comment]
Hello,

Strange...works for me when I am reloading the page(sending the request to
the page).

**Comment by jansivans** [comment]
Here you can see a price returned from your endpoint stays at `9097.3847` (I have tried to refresh several times).
Actual price should be `9094.9873`.

![image](https://user-images.githubusercontent.com/5667073/95184099-8ff8bd00-07cf-11eb-9d40-d46dbad5be1e.png)

**Comment by RusKrim** [comment]
Ahh,yes, it was probably the requrest I made with async function getr(). I
have udpdated my repo yesterday. I have this code working well:
request.get(
  "https://api.coindesk.com/v1/bpi/currentprice.json",
  (err, res, body) => {
    if (err) throw err;
    const json = JSON.parse(body);
    const jsonEur = json.bpi.EUR;
    console.log(jsonEur);
    app.get("/btc", (req, res) => {
      console.log(`Price of BTC is ${jsonEur.rate_float} ${jsonEur.code}`);
      res.send(
        `<h1>Price of BTC is ${jsonEur.rate_float} ${jsonEur.code}</h1>`
      );
    });
  }
);

**Comment by RusKrim** [comment]
Thanks, I saw the problem. I will fix it Asap

**Comment by jansivans** [comment]
I have tested latest version of your code.
As a hint I will tell you that the main problem is where `request.get` and `app.get` are located.

**Comment by jansivans** [comment]
I have tested latest version of your code.
As a hint I will tell you that the main problem is where `request.get` and `app.get` are located.

**Comment by RusKrim** [comment]
Hello,

I was too busy with my subjects at university. Currently I have done 2
endpoints. 1st endpoint returns a dynamic value, 2nd endpoint returns the
message with the needed country. Moving to the 3rd one.

Kind regards,

Ruslans Krims

**Comment by RusKrim** [comment]
Am I moving to the right direction?

**Comment by jansivans** [comment]
Seems good so far.

**Comment by RusKrim** [comment]
Good evening, the task is done. I have left a summary in the Read.me file

**Comment by jansivans** [comment]
Thank you!
Now it looks like everything is done.
I can only add that setting up multer could be done much easier.
Just use this code:
```js
const multer = require('multer');
const upload = multer({ dest: 'uploads/' });
```
And when defining your endpoint do this:
```js
app.post('/excel-sum', upload.single('file'), async function (req, res) {
```
Overall great. I see that you have learned much by doing this task.
Please `await` a response from HR manager.
